//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQtoEFExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Master()
        {
            this.Book_Transaction = new HashSet<Book_Transaction>();
        }
    
        public decimal Book_code { get; set; }
        public string Book_name { get; set; }
        public Nullable<int> pub_year { get; set; }
        public string Author { get; set; }
        public string book_category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Transaction> Book_Transaction { get; set; }
    }
}
