//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQtoEFExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_master()
        {
            this.Book_Transaction = new HashSet<Book_Transaction>();
            this.Student_Marks = new HashSet<Student_Marks>();
        }
    
        public decimal Stud_Code { get; set; }
        public string Stud_Name { get; set; }
        public Nullable<decimal> Dept_Code { get; set; }
        public Nullable<System.DateTime> Stud_Dob { get; set; }
        public string Address { get; set; }
    
        public virtual Department_master Department_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Transaction> Book_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Marks> Student_Marks { get; set; }
    }
}
