
SELECT * INTO AGENT1
FROM AGENT  
WHERE AGENTID BETWEEN 1 AND 10 


SELECT * INTO AGENT2
FROM AGENT  
WHERE AGENTID BETWEEN 7 AND 30 

SELECT AGENTID,FIRSTNAME,LASTNAME,CITY,SSN 
FROM AGENT1 
INTERSECT
SELECT AGENTID,FIRSTNAME,LASTNAME,CITY,SSN 
FROM AGENT2 

SELECT AGENTID,FIRSTNAME,LASTNAME,CITY,SSN 
FROM AGENT1 
UNION 
SELECT AGENTID,FIRSTNAME,LASTNAME,CITY,SSN 
FROM AGENT2 

SELECT AGENTID,FIRSTNAME,LASTNAME,CITY,SSN 
FROM AGENT1 
EXCEPT 
SELECT AGENTID,FIRSTNAME,LASTNAME,CITY,SSN 
FROM AGENT2 