//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQtoEFExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Transaction
    {
        public Nullable<decimal> Book_code { get; set; }
        public Nullable<decimal> Stud_code { get; set; }
        public Nullable<decimal> Staff_code { get; set; }
        public System.DateTime Issue_date { get; set; }
        public System.DateTime Exp_Return_date { get; set; }
        public Nullable<System.DateTime> Actual_Return_date { get; set; }
    
        public virtual Book_Master Book_Master { get; set; }
        public virtual Staff_Master Staff_Master { get; set; }
        public virtual Student_master Student_master { get; set; }
    }
}
