//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQtoEFExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff_Master()
        {
            this.Book_Transaction = new HashSet<Book_Transaction>();
        }
    
        public decimal Staff_Code { get; set; }
        public string Staff_Name { get; set; }
        public Nullable<decimal> Des_Code { get; set; }
        public Nullable<decimal> Dept_Code { get; set; }
        public Nullable<System.DateTime> Staff_dob { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
        public Nullable<decimal> Mgr_code { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Address { get; set; }
    
        public virtual Department_master Department_master { get; set; }
        public virtual Desig_master Desig_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_Transaction> Book_Transaction { get; set; }
    }
}
