//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQtoEFExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingEntities : DbContext
    {
        public TrainingEntities()
            : base("name=TrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_Master> Book_Master { get; set; }
        public virtual DbSet<Department_master> Department_master { get; set; }
        public virtual DbSet<Desig_master> Desig_master { get; set; }
        public virtual DbSet<Staff_Master> Staff_Master { get; set; }
        public virtual DbSet<Student_master> Student_master { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Book_Transaction> Book_Transaction { get; set; }
        public virtual DbSet<Student_Marks> Student_Marks { get; set; }
    }
}
