//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstApproachEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Master
    {
        public decimal Staff_Code { get; set; }
        public string Staff_Name { get; set; }
        public Nullable<decimal> Des_Code { get; set; }
        public Nullable<decimal> Dept_Code { get; set; }
        public Nullable<System.DateTime> Staff_dob { get; set; }
        public Nullable<System.DateTime> Hiredate { get; set; }
        public Nullable<decimal> Mgr_code { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Address { get; set; }
    }
}
