USE PRACTICE 
GO

CREATE SEQUENCE SeqAgent START WITH 1 INCREMENT BY 1

IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='AGENT') 
DROP TABLE AGENT 

CREATE TABLE AGENT
(
   AGENTID INT
   CONSTRAINT PK_AGENT_AgentID PRIMARY KEY(AGENTID),
   NAME VARCHAR(30),
   CITY VARCHAR(30)
)
GO

INSERT INTO AGENT(AGENTID,NAME,CITY) 
VALUES (NEXT VALUE FOR SeqAgent,'Arun','Chennai'),
   (NEXT VALUE FOR SeqAgent,'Sangeetha','Bhuvaneswar'),
   (NEXT VALUE FOR SeqAgent,'Aruna','Kadapa'),
   (NEXT VALUE FOR SeqAgent,'Anusha','Hyderabad')
GO

SELECT * FROM AGENT 
GO
