IF EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME='EMPTEST')
DROP TABLE EMPTEST 
GO

CREATE TABLE EMPTEST
(
   EMPNO INT,
   NAME VARCHAR(30),
   DEPT VARCHAR(30),
   DESIG VARCHAR(30),
   SALARY INT
)
GO

INSERT INTO EMPTEST VALUES(12,'ARUN','DOTNET','PROGRAMMER',42234),
						 (8,'SIVA','JAVA','DEVELOPER',28442),
						 (10,'ANU','SQL','EXPERT',82134),
						 (9,'PALLAVI','DOTNET','TL',81344),
						 (13,'SANGEETHA','DOTNET','TL',54344),
						 (11,'DHIVYA','SQL','DEVELOPER',82344)
GO

CREATE CLUSTERED INDEX IDX_EMP_EMPNO 
ON EMPTEST(EMPNO)

SELECT * FROM EMPTEST 
GO

CREATE NONCLUSTERED INDEX IDX_EMP_NAME
ON EMPTEST(NAME)

CREATE INDEX IDX_EMP_DEPT
ON EMPTEST(DEPT)

